export default postsByTopic = [
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Opera Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1590363174598,
  },
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Opera Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1590163174198,
  },
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Opera Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1590113174198,
  },
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Opera Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1520113174198,
  },
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1520713174198,
  },
  {
    assets: "",
    category: "Read",
    focus: "Grammar",
    iconPath: "posts/1590279183391-default.png",
    post: { about: "", conclusion: "", content: "" },
    subCategory: "Culture",
    title: "Opera Singer by Day, Janitor by Night",
    uid: "-M82hXciwXZh9tLQw5PO",
    date: 1520413174198,
  },
];
